#![doc = "Peripheral access API for RP2350 microcontrollers (generated using svd2rust v0.36.0 ( ))  

You can find an overview of the generated API [here].  

API features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.  

[here]: https://docs.rs/svd2rust/0.36.0/svd2rust/#peripheral-api  
[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased  
[repository]: https://github.com/rust-embedded/svd2rust"]
#[doc = r"Number available in the NVIC for configuring priority"]
pub const NVIC_PRIO_BITS: u8 = 4;
#[cfg(feature = "rt")]
pub use self::Interrupt as interrupt;
#[cfg(feature = "rt")]
pub use cortex_m_rt::interrupt;
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
extern "C" {
    fn TIMER0_IRQ_0();
    fn TIMER0_IRQ_1();
    fn TIMER0_IRQ_2();
    fn TIMER0_IRQ_3();
    fn TIMER1_IRQ_0();
    fn TIMER1_IRQ_1();
    fn TIMER1_IRQ_2();
    fn TIMER1_IRQ_3();
    fn PWM_IRQ_WRAP_0();
    fn PWM_IRQ_WRAP_1();
    fn DMA_IRQ_0();
    fn DMA_IRQ_1();
    fn DMA_IRQ_2();
    fn DMA_IRQ_3();
    fn USBCTRL_IRQ();
    fn PIO0_IRQ_0();
    fn PIO0_IRQ_1();
    fn PIO1_IRQ_0();
    fn PIO1_IRQ_1();
    fn PIO2_IRQ_0();
    fn PIO2_IRQ_1();
    fn IO_IRQ_BANK0();
    fn IO_IRQ_BANK0_NS();
    fn IO_IRQ_QSPI();
    fn IO_IRQ_QSPI_NS();
    fn SIO_IRQ_FIFO();
    fn SIO_IRQ_BELL();
    fn SIO_IRQ_FIFO_NS();
    fn SIO_IRQ_BELL_NS();
    fn SIO_IRQ_MTIMECMP();
    fn CLOCKS_IRQ();
    fn SPI0_IRQ();
    fn SPI1_IRQ();
    fn UART0_IRQ();
    fn UART1_IRQ();
    fn ADC_IRQ_FIFO();
    fn I2C0_IRQ();
    fn I2C1_IRQ();
    fn OTP_IRQ();
    fn TRNG_IRQ();
    fn PLL_SYS_IRQ();
    fn PLL_USB_IRQ();
    fn POWMAN_IRQ_POW();
    fn POWMAN_IRQ_TIMER();
    fn SW0_IRQ();
    fn SW1_IRQ();
    fn SW2_IRQ();
    fn SW3_IRQ();
    fn SW4_IRQ();
    fn SW5_IRQ();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
pub static __INTERRUPTS: [Vector; 52] = [
    Vector {
        _handler: TIMER0_IRQ_0,
    },
    Vector {
        _handler: TIMER0_IRQ_1,
    },
    Vector {
        _handler: TIMER0_IRQ_2,
    },
    Vector {
        _handler: TIMER0_IRQ_3,
    },
    Vector {
        _handler: TIMER1_IRQ_0,
    },
    Vector {
        _handler: TIMER1_IRQ_1,
    },
    Vector {
        _handler: TIMER1_IRQ_2,
    },
    Vector {
        _handler: TIMER1_IRQ_3,
    },
    Vector {
        _handler: PWM_IRQ_WRAP_0,
    },
    Vector {
        _handler: PWM_IRQ_WRAP_1,
    },
    Vector {
        _handler: DMA_IRQ_0,
    },
    Vector {
        _handler: DMA_IRQ_1,
    },
    Vector {
        _handler: DMA_IRQ_2,
    },
    Vector {
        _handler: DMA_IRQ_3,
    },
    Vector {
        _handler: USBCTRL_IRQ,
    },
    Vector {
        _handler: PIO0_IRQ_0,
    },
    Vector {
        _handler: PIO0_IRQ_1,
    },
    Vector {
        _handler: PIO1_IRQ_0,
    },
    Vector {
        _handler: PIO1_IRQ_1,
    },
    Vector {
        _handler: PIO2_IRQ_0,
    },
    Vector {
        _handler: PIO2_IRQ_1,
    },
    Vector {
        _handler: IO_IRQ_BANK0,
    },
    Vector {
        _handler: IO_IRQ_BANK0_NS,
    },
    Vector {
        _handler: IO_IRQ_QSPI,
    },
    Vector {
        _handler: IO_IRQ_QSPI_NS,
    },
    Vector {
        _handler: SIO_IRQ_FIFO,
    },
    Vector {
        _handler: SIO_IRQ_BELL,
    },
    Vector {
        _handler: SIO_IRQ_FIFO_NS,
    },
    Vector {
        _handler: SIO_IRQ_BELL_NS,
    },
    Vector {
        _handler: SIO_IRQ_MTIMECMP,
    },
    Vector {
        _handler: CLOCKS_IRQ,
    },
    Vector { _handler: SPI0_IRQ },
    Vector { _handler: SPI1_IRQ },
    Vector {
        _handler: UART0_IRQ,
    },
    Vector {
        _handler: UART1_IRQ,
    },
    Vector {
        _handler: ADC_IRQ_FIFO,
    },
    Vector { _handler: I2C0_IRQ },
    Vector { _handler: I2C1_IRQ },
    Vector { _handler: OTP_IRQ },
    Vector { _handler: TRNG_IRQ },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector {
        _handler: PLL_SYS_IRQ,
    },
    Vector {
        _handler: PLL_USB_IRQ,
    },
    Vector {
        _handler: POWMAN_IRQ_POW,
    },
    Vector {
        _handler: POWMAN_IRQ_TIMER,
    },
    Vector { _handler: SW0_IRQ },
    Vector { _handler: SW1_IRQ },
    Vector { _handler: SW2_IRQ },
    Vector { _handler: SW3_IRQ },
    Vector { _handler: SW4_IRQ },
    Vector { _handler: SW5_IRQ },
];
#[doc = r"Enumeration of all the interrupts."]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "0 - TIMER0_IRQ_0"]
    TIMER0_IRQ_0 = 0,
    #[doc = "1 - TIMER0_IRQ_1"]
    TIMER0_IRQ_1 = 1,
    #[doc = "2 - TIMER0_IRQ_2"]
    TIMER0_IRQ_2 = 2,
    #[doc = "3 - TIMER0_IRQ_3"]
    TIMER0_IRQ_3 = 3,
    #[doc = "4 - TIMER1_IRQ_0"]
    TIMER1_IRQ_0 = 4,
    #[doc = "5 - TIMER1_IRQ_1"]
    TIMER1_IRQ_1 = 5,
    #[doc = "6 - TIMER1_IRQ_2"]
    TIMER1_IRQ_2 = 6,
    #[doc = "7 - TIMER1_IRQ_3"]
    TIMER1_IRQ_3 = 7,
    #[doc = "8 - PWM_IRQ_WRAP_0"]
    PWM_IRQ_WRAP_0 = 8,
    #[doc = "9 - PWM_IRQ_WRAP_1"]
    PWM_IRQ_WRAP_1 = 9,
    #[doc = "10 - DMA_IRQ_0"]
    DMA_IRQ_0 = 10,
    #[doc = "11 - DMA_IRQ_1"]
    DMA_IRQ_1 = 11,
    #[doc = "12 - DMA_IRQ_2"]
    DMA_IRQ_2 = 12,
    #[doc = "13 - DMA_IRQ_3"]
    DMA_IRQ_3 = 13,
    #[doc = "14 - USBCTRL_IRQ"]
    USBCTRL_IRQ = 14,
    #[doc = "15 - PIO0_IRQ_0"]
    PIO0_IRQ_0 = 15,
    #[doc = "16 - PIO0_IRQ_1"]
    PIO0_IRQ_1 = 16,
    #[doc = "17 - PIO1_IRQ_0"]
    PIO1_IRQ_0 = 17,
    #[doc = "18 - PIO1_IRQ_1"]
    PIO1_IRQ_1 = 18,
    #[doc = "19 - PIO2_IRQ_0"]
    PIO2_IRQ_0 = 19,
    #[doc = "20 - PIO2_IRQ_1"]
    PIO2_IRQ_1 = 20,
    #[doc = "21 - IO_IRQ_BANK0"]
    IO_IRQ_BANK0 = 21,
    #[doc = "22 - IO_IRQ_BANK0_NS"]
    IO_IRQ_BANK0_NS = 22,
    #[doc = "23 - IO_IRQ_QSPI"]
    IO_IRQ_QSPI = 23,
    #[doc = "24 - IO_IRQ_QSPI_NS"]
    IO_IRQ_QSPI_NS = 24,
    #[doc = "25 - SIO_IRQ_FIFO"]
    SIO_IRQ_FIFO = 25,
    #[doc = "26 - SIO_IRQ_BELL"]
    SIO_IRQ_BELL = 26,
    #[doc = "27 - SIO_IRQ_FIFO_NS"]
    SIO_IRQ_FIFO_NS = 27,
    #[doc = "28 - SIO_IRQ_BELL_NS"]
    SIO_IRQ_BELL_NS = 28,
    #[doc = "29 - SIO_IRQ_MTIMECMP"]
    SIO_IRQ_MTIMECMP = 29,
    #[doc = "30 - CLOCKS_IRQ"]
    CLOCKS_IRQ = 30,
    #[doc = "31 - SPI0_IRQ"]
    SPI0_IRQ = 31,
    #[doc = "32 - SPI1_IRQ"]
    SPI1_IRQ = 32,
    #[doc = "33 - UART0_IRQ"]
    UART0_IRQ = 33,
    #[doc = "34 - UART1_IRQ"]
    UART1_IRQ = 34,
    #[doc = "35 - ADC_IRQ_FIFO"]
    ADC_IRQ_FIFO = 35,
    #[doc = "36 - I2C0_IRQ"]
    I2C0_IRQ = 36,
    #[doc = "37 - I2C1_IRQ"]
    I2C1_IRQ = 37,
    #[doc = "38 - OTP_IRQ"]
    OTP_IRQ = 38,
    #[doc = "39 - TRNG_IRQ"]
    TRNG_IRQ = 39,
    #[doc = "42 - PLL_SYS_IRQ"]
    PLL_SYS_IRQ = 42,
    #[doc = "43 - PLL_USB_IRQ"]
    PLL_USB_IRQ = 43,
    #[doc = "44 - POWMAN_IRQ_POW"]
    POWMAN_IRQ_POW = 44,
    #[doc = "45 - POWMAN_IRQ_TIMER"]
    POWMAN_IRQ_TIMER = 45,
    #[doc = "46 - Spare IRQ 0"]
    SW0_IRQ = 46,
    #[doc = "47 - Spare IRQ 1"]
    SW1_IRQ = 47,
    #[doc = "48 - Spare IRQ 2"]
    SW2_IRQ = 48,
    #[doc = "49 - Spare IRQ 3"]
    SW3_IRQ = 49,
    #[doc = "50 - Spare IRQ 4"]
    SW4_IRQ = 50,
    #[doc = "51 - Spare IRQ 5"]
    SW5_IRQ = 51,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[doc = "RESETS"]
pub type RESETS = crate::Periph<resets::RegisterBlock, 0x4002_0000>;
impl core::fmt::Debug for RESETS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("RESETS").finish()
    }
}
#[doc = "RESETS"]
pub mod resets;
#[doc = "PSM"]
pub type PSM = crate::Periph<psm::RegisterBlock, 0x4001_8000>;
impl core::fmt::Debug for PSM {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PSM").finish()
    }
}
#[doc = "PSM"]
pub mod psm;
#[doc = "CLOCKS"]
pub type CLOCKS = crate::Periph<clocks::RegisterBlock, 0x4001_0000>;
impl core::fmt::Debug for CLOCKS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CLOCKS").finish()
    }
}
#[doc = "CLOCKS"]
pub mod clocks;
#[doc = "TICKS"]
pub type TICKS = crate::Periph<ticks::RegisterBlock, 0x4010_8000>;
impl core::fmt::Debug for TICKS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TICKS").finish()
    }
}
#[doc = "TICKS"]
pub mod ticks;
#[doc = "PADS_BANK0"]
pub type PADS_BANK0 = crate::Periph<pads_bank0::RegisterBlock, 0x4003_8000>;
impl core::fmt::Debug for PADS_BANK0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PADS_BANK0").finish()
    }
}
#[doc = "PADS_BANK0"]
pub mod pads_bank0;
#[doc = "PADS_QSPI"]
pub type PADS_QSPI = crate::Periph<pads_qspi::RegisterBlock, 0x4004_0000>;
impl core::fmt::Debug for PADS_QSPI {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PADS_QSPI").finish()
    }
}
#[doc = "PADS_QSPI"]
pub mod pads_qspi;
#[doc = "IO_QSPI"]
pub type IO_QSPI = crate::Periph<io_qspi::RegisterBlock, 0x4003_0000>;
impl core::fmt::Debug for IO_QSPI {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("IO_QSPI").finish()
    }
}
#[doc = "IO_QSPI"]
pub mod io_qspi;
#[doc = "IO_BANK0"]
pub type IO_BANK0 = crate::Periph<io_bank0::RegisterBlock, 0x4002_8000>;
impl core::fmt::Debug for IO_BANK0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("IO_BANK0").finish()
    }
}
#[doc = "IO_BANK0"]
pub mod io_bank0;
#[doc = "SYSINFO"]
pub type SYSINFO = crate::Periph<sysinfo::RegisterBlock, 0x4000_0000>;
impl core::fmt::Debug for SYSINFO {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SYSINFO").finish()
    }
}
#[doc = "SYSINFO"]
pub mod sysinfo;
#[doc = "SHA-256 hash function implementation"]
pub type SHA256 = crate::Periph<sha256::RegisterBlock, 0x400f_8000>;
impl core::fmt::Debug for SHA256 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SHA256").finish()
    }
}
#[doc = "SHA-256 hash function implementation"]
pub mod sha256;
#[doc = "FIFO status and write access for HSTX"]
pub type HSTX_FIFO = crate::Periph<hstx_fifo::RegisterBlock, 0x5060_0000>;
impl core::fmt::Debug for HSTX_FIFO {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("HSTX_FIFO").finish()
    }
}
#[doc = "FIFO status and write access for HSTX"]
pub mod hstx_fifo;
#[doc = "Control interface to HSTX. For FIFO write access and status, see the HSTX_FIFO register block."]
pub type HSTX_CTRL = crate::Periph<hstx_ctrl::RegisterBlock, 0x400c_0000>;
impl core::fmt::Debug for HSTX_CTRL {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("HSTX_CTRL").finish()
    }
}
#[doc = "Control interface to HSTX. For FIFO write access and status, see the HSTX_FIFO register block."]
pub mod hstx_ctrl;
#[doc = "Cortex-M33 EPPB vendor register block for RP2350"]
pub type EPPB = crate::Periph<eppb::RegisterBlock, 0xe008_0000>;
impl core::fmt::Debug for EPPB {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("EPPB").finish()
    }
}
#[doc = "Cortex-M33 EPPB vendor register block for RP2350"]
pub mod eppb;
#[doc = "TEAL registers accessible through the debug interface"]
pub type PPB = crate::Periph<ppb::RegisterBlock, 0xe000_0000>;
impl core::fmt::Debug for PPB {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PPB").finish()
    }
}
#[doc = "TEAL registers accessible through the debug interface"]
pub mod ppb;
#[doc = "TEAL registers accessible through the debug interface"]
pub type PPB_NS = crate::Periph<ppb::RegisterBlock, 0xe002_0000>;
impl core::fmt::Debug for PPB_NS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PPB_NS").finish()
    }
}
#[doc = "TEAL registers accessible through the debug interface"]
pub use self::ppb as ppb_ns;
#[doc = "QSPI Memory Interface.  

 Provides a memory-mapped interface to up to two SPI/DSPI/QSPI flash or PSRAM devices. Also provides a serial interface for programming and configuration of the external device."]
pub type QMI = crate::Periph<qmi::RegisterBlock, 0x400d_0000>;
impl core::fmt::Debug for QMI {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("QMI").finish()
    }
}
#[doc = "QSPI Memory Interface.  

 Provides a memory-mapped interface to up to two SPI/DSPI/QSPI flash or PSRAM devices. Also provides a serial interface for programming and configuration of the external device."]
pub mod qmi;
#[doc = "QSPI flash execute-in-place block"]
pub type XIP_CTRL = crate::Periph<xip_ctrl::RegisterBlock, 0x400c_8000>;
impl core::fmt::Debug for XIP_CTRL {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("XIP_CTRL").finish()
    }
}
#[doc = "QSPI flash execute-in-place block"]
pub mod xip_ctrl;
#[doc = "Auxiliary DMA access to XIP FIFOs, via fast AHB bus access"]
pub type XIP_AUX = crate::Periph<xip_aux::RegisterBlock, 0x5050_0000>;
impl core::fmt::Debug for XIP_AUX {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("XIP_AUX").finish()
    }
}
#[doc = "Auxiliary DMA access to XIP FIFOs, via fast AHB bus access"]
pub mod xip_aux;
#[doc = "Register block for various chip control signals"]
pub type SYSCFG = crate::Periph<syscfg::RegisterBlock, 0x4000_8000>;
impl core::fmt::Debug for SYSCFG {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SYSCFG").finish()
    }
}
#[doc = "Register block for various chip control signals"]
pub mod syscfg;
#[doc = "Controls the crystal oscillator"]
pub type XOSC = crate::Periph<xosc::RegisterBlock, 0x4004_8000>;
impl core::fmt::Debug for XOSC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("XOSC").finish()
    }
}
#[doc = "Controls the crystal oscillator"]
pub mod xosc;
#[doc = "PLL_SYS"]
pub type PLL_SYS = crate::Periph<pll_sys::RegisterBlock, 0x4005_0000>;
impl core::fmt::Debug for PLL_SYS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PLL_SYS").finish()
    }
}
#[doc = "PLL_SYS"]
pub mod pll_sys;
#[doc = "PLL_USB"]
pub type PLL_USB = crate::Periph<pll_sys::RegisterBlock, 0x4005_8000>;
impl core::fmt::Debug for PLL_USB {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PLL_USB").finish()
    }
}
#[doc = "PLL_USB"]
pub use self::pll_sys as pll_usb;
#[doc = "Hardware access control registers"]
pub type ACCESSCTRL = crate::Periph<accessctrl::RegisterBlock, 0x4006_0000>;
impl core::fmt::Debug for ACCESSCTRL {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("ACCESSCTRL").finish()
    }
}
#[doc = "Hardware access control registers"]
pub mod accessctrl;
#[doc = "UART0"]
pub type UART0 = crate::Periph<uart0::RegisterBlock, 0x4007_0000>;
impl core::fmt::Debug for UART0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UART0").finish()
    }
}
#[doc = "UART0"]
pub mod uart0;
#[doc = "UART1"]
pub type UART1 = crate::Periph<uart0::RegisterBlock, 0x4007_8000>;
impl core::fmt::Debug for UART1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UART1").finish()
    }
}
#[doc = "UART1"]
pub use self::uart0 as uart1;
#[doc = "ROSC"]
pub type ROSC = crate::Periph<rosc::RegisterBlock, 0x400e_8000>;
impl core::fmt::Debug for ROSC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("ROSC").finish()
    }
}
#[doc = "ROSC"]
pub mod rosc;
#[doc = "Controls vreg, bor, lposc, chip resets & xosc startup, powman and provides scratch register for general use and for bootcode use"]
pub type POWMAN = crate::Periph<powman::RegisterBlock, 0x4010_0000>;
impl core::fmt::Debug for POWMAN {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("POWMAN").finish()
    }
}
#[doc = "Controls vreg, bor, lposc, chip resets & xosc startup, powman and provides scratch register for general use and for bootcode use"]
pub mod powman;
#[doc = "WATCHDOG"]
pub type WATCHDOG = crate::Periph<watchdog::RegisterBlock, 0x400d_8000>;
impl core::fmt::Debug for WATCHDOG {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("WATCHDOG").finish()
    }
}
#[doc = "WATCHDOG"]
pub mod watchdog;
#[doc = "DMA with separate read and write masters"]
pub type DMA = crate::Periph<dma::RegisterBlock, 0x5000_0000>;
impl core::fmt::Debug for DMA {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DMA").finish()
    }
}
#[doc = "DMA with separate read and write masters"]
pub mod dma;
#[doc = "Controls time and alarms  

 time is a 64 bit value indicating the time since power-on  

 timeh is the top 32 bits of time & timel is the bottom 32 bits to change time write to timelw before timehw to read time read from timelr before timehr  

 An alarm is set by setting alarm_enable and writing to the corresponding alarm register When an alarm is pending, the corresponding alarm_running signal will be high An alarm can be cancelled before it has finished by clearing the alarm_enable When an alarm fires, the corresponding alarm_irq is set and alarm_running is cleared To clear the interrupt write a 1 to the corresponding alarm_irq The timer can be locked to prevent writing"]
pub type TIMER0 = crate::Periph<timer0::RegisterBlock, 0x400b_0000>;
impl core::fmt::Debug for TIMER0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TIMER0").finish()
    }
}
#[doc = "Controls time and alarms  

 time is a 64 bit value indicating the time since power-on  

 timeh is the top 32 bits of time & timel is the bottom 32 bits to change time write to timelw before timehw to read time read from timelr before timehr  

 An alarm is set by setting alarm_enable and writing to the corresponding alarm register When an alarm is pending, the corresponding alarm_running signal will be high An alarm can be cancelled before it has finished by clearing the alarm_enable When an alarm fires, the corresponding alarm_irq is set and alarm_running is cleared To clear the interrupt write a 1 to the corresponding alarm_irq The timer can be locked to prevent writing"]
pub mod timer0;
#[doc = "Controls time and alarms  

 time is a 64 bit value indicating the time since power-on  

 timeh is the top 32 bits of time & timel is the bottom 32 bits to change time write to timelw before timehw to read time read from timelr before timehr  

 An alarm is set by setting alarm_enable and writing to the corresponding alarm register When an alarm is pending, the corresponding alarm_running signal will be high An alarm can be cancelled before it has finished by clearing the alarm_enable When an alarm fires, the corresponding alarm_irq is set and alarm_running is cleared To clear the interrupt write a 1 to the corresponding alarm_irq The timer can be locked to prevent writing"]
pub type TIMER1 = crate::Periph<timer0::RegisterBlock, 0x400b_8000>;
impl core::fmt::Debug for TIMER1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TIMER1").finish()
    }
}
#[doc = "Controls time and alarms  

 time is a 64 bit value indicating the time since power-on  

 timeh is the top 32 bits of time & timel is the bottom 32 bits to change time write to timelw before timehw to read time read from timelr before timehr  

 An alarm is set by setting alarm_enable and writing to the corresponding alarm register When an alarm is pending, the corresponding alarm_running signal will be high An alarm can be cancelled before it has finished by clearing the alarm_enable When an alarm fires, the corresponding alarm_irq is set and alarm_running is cleared To clear the interrupt write a 1 to the corresponding alarm_irq The timer can be locked to prevent writing"]
pub use self::timer0 as timer1;
#[doc = "Simple PWM"]
pub type PWM = crate::Periph<pwm::RegisterBlock, 0x400a_8000>;
impl core::fmt::Debug for PWM {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PWM").finish()
    }
}
#[doc = "Simple PWM"]
pub mod pwm;
#[doc = "Control and data interface to SAR ADC"]
pub type ADC = crate::Periph<adc::RegisterBlock, 0x400a_0000>;
impl core::fmt::Debug for ADC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("ADC").finish()
    }
}
#[doc = "Control and data interface to SAR ADC"]
pub mod adc;
#[doc = "DW_apb_i2c address block  

 List of configuration constants for the Synopsys I2C hardware (you may see references to these in I2C register header; these are *fixed* values, set at hardware design time):  

 IC_ULTRA_FAST_MODE ................ 0x0   
 IC_UFM_TBUF_CNT_DEFAULT ........... 0x8   
 IC_UFM_SCL_LOW_COUNT .............. 0x0008   
 IC_UFM_SCL_HIGH_COUNT ............. 0x0006   
 IC_TX_TL .......................... 0x0   
 IC_TX_CMD_BLOCK ................... 0x1   
 IC_HAS_DMA ........................ 0x1   
 IC_HAS_ASYNC_FIFO ................. 0x0   
 IC_SMBUS_ARP ...................... 0x0   
 IC_FIRST_DATA_BYTE_STATUS ......... 0x1   
 IC_INTR_IO ........................ 0x1   
 IC_MASTER_MODE .................... 0x1   
 IC_DEFAULT_ACK_GENERAL_CALL ....... 0x1   
 IC_INTR_POL ....................... 0x1   
 IC_OPTIONAL_SAR ................... 0x0   
 IC_DEFAULT_TAR_SLAVE_ADDR ......... 0x055   
 IC_DEFAULT_SLAVE_ADDR ............. 0x055   
 IC_DEFAULT_HS_SPKLEN .............. 0x1   
 IC_FS_SCL_HIGH_COUNT .............. 0x0006   
 IC_HS_SCL_LOW_COUNT ............... 0x0008   
 IC_DEVICE_ID_VALUE ................ 0x0   
 IC_10BITADDR_MASTER ............... 0x0   
 IC_CLK_FREQ_OPTIMIZATION .......... 0x0   
 IC_DEFAULT_FS_SPKLEN .............. 0x7   
 IC_ADD_ENCODED_PARAMS ............. 0x0   
 IC_DEFAULT_SDA_HOLD ............... 0x000001   
 IC_DEFAULT_SDA_SETUP .............. 0x64   
 IC_AVOID_RX_FIFO_FLUSH_ON_TX_ABRT . 0x0   
 IC_CLOCK_PERIOD ................... 100   
 IC_EMPTYFIFO_HOLD_MASTER_EN ....... 1   
 IC_RESTART_EN ..................... 0x1   
 IC_TX_CMD_BLOCK_DEFAULT ........... 0x0   
 IC_BUS_CLEAR_FEATURE .............. 0x0   
 IC_CAP_LOADING .................... 100   
 IC_FS_SCL_LOW_COUNT ............... 0x000d   
 APB_DATA_WIDTH .................... 32   
 IC_SDA_STUCK_TIMEOUT_DEFAULT ...... 0xffffffff   
 IC_SLV_DATA_NACK_ONLY ............. 0x1   
 IC_10BITADDR_SLAVE ................ 0x0   
 IC_CLK_TYPE ....................... 0x0   
 IC_SMBUS_UDID_MSB ................. 0x0   
 IC_SMBUS_SUSPEND_ALERT ............ 0x0   
 IC_HS_SCL_HIGH_COUNT .............. 0x0006   
 IC_SLV_RESTART_DET_EN ............. 0x1   
 IC_SMBUS .......................... 0x0   
 IC_OPTIONAL_SAR_DEFAULT ........... 0x0   
 IC_PERSISTANT_SLV_ADDR_DEFAULT .... 0x0   
 IC_USE_COUNTS ..................... 0x0   
 IC_RX_BUFFER_DEPTH ................ 16   
 IC_SCL_STUCK_TIMEOUT_DEFAULT ...... 0xffffffff   
 IC_RX_FULL_HLD_BUS_EN ............. 0x1   
 IC_SLAVE_DISABLE .................. 0x1   
 IC_RX_TL .......................... 0x0   
 IC_DEVICE_ID ...................... 0x0   
 IC_HC_COUNT_VALUES ................ 0x0   
 I2C_DYNAMIC_TAR_UPDATE ............ 0   
 IC_SMBUS_CLK_LOW_MEXT_DEFAULT ..... 0xffffffff   
 IC_SMBUS_CLK_LOW_SEXT_DEFAULT ..... 0xffffffff   
 IC_HS_MASTER_CODE ................. 0x1   
 IC_SMBUS_RST_IDLE_CNT_DEFAULT ..... 0xffff   
 IC_SMBUS_UDID_LSB_DEFAULT ......... 0xffffffff   
 IC_SS_SCL_HIGH_COUNT .............. 0x0028   
 IC_SS_SCL_LOW_COUNT ............... 0x002f   
 IC_MAX_SPEED_MODE ................. 0x2   
 IC_STAT_FOR_CLK_STRETCH ........... 0x0   
 IC_STOP_DET_IF_MASTER_ACTIVE ...... 0x0   
 IC_DEFAULT_UFM_SPKLEN ............. 0x1   
 IC_TX_BUFFER_DEPTH ................ 16"]
pub type I2C0 = crate::Periph<i2c0::RegisterBlock, 0x4009_0000>;
impl core::fmt::Debug for I2C0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2C0").finish()
    }
}
#[doc = "DW_apb_i2c address block  

 List of configuration constants for the Synopsys I2C hardware (you may see references to these in I2C register header; these are *fixed* values, set at hardware design time):  

 IC_ULTRA_FAST_MODE ................ 0x0   
 IC_UFM_TBUF_CNT_DEFAULT ........... 0x8   
 IC_UFM_SCL_LOW_COUNT .............. 0x0008   
 IC_UFM_SCL_HIGH_COUNT ............. 0x0006   
 IC_TX_TL .......................... 0x0   
 IC_TX_CMD_BLOCK ................... 0x1   
 IC_HAS_DMA ........................ 0x1   
 IC_HAS_ASYNC_FIFO ................. 0x0   
 IC_SMBUS_ARP ...................... 0x0   
 IC_FIRST_DATA_BYTE_STATUS ......... 0x1   
 IC_INTR_IO ........................ 0x1   
 IC_MASTER_MODE .................... 0x1   
 IC_DEFAULT_ACK_GENERAL_CALL ....... 0x1   
 IC_INTR_POL ....................... 0x1   
 IC_OPTIONAL_SAR ................... 0x0   
 IC_DEFAULT_TAR_SLAVE_ADDR ......... 0x055   
 IC_DEFAULT_SLAVE_ADDR ............. 0x055   
 IC_DEFAULT_HS_SPKLEN .............. 0x1   
 IC_FS_SCL_HIGH_COUNT .............. 0x0006   
 IC_HS_SCL_LOW_COUNT ............... 0x0008   
 IC_DEVICE_ID_VALUE ................ 0x0   
 IC_10BITADDR_MASTER ............... 0x0   
 IC_CLK_FREQ_OPTIMIZATION .......... 0x0   
 IC_DEFAULT_FS_SPKLEN .............. 0x7   
 IC_ADD_ENCODED_PARAMS ............. 0x0   
 IC_DEFAULT_SDA_HOLD ............... 0x000001   
 IC_DEFAULT_SDA_SETUP .............. 0x64   
 IC_AVOID_RX_FIFO_FLUSH_ON_TX_ABRT . 0x0   
 IC_CLOCK_PERIOD ................... 100   
 IC_EMPTYFIFO_HOLD_MASTER_EN ....... 1   
 IC_RESTART_EN ..................... 0x1   
 IC_TX_CMD_BLOCK_DEFAULT ........... 0x0   
 IC_BUS_CLEAR_FEATURE .............. 0x0   
 IC_CAP_LOADING .................... 100   
 IC_FS_SCL_LOW_COUNT ............... 0x000d   
 APB_DATA_WIDTH .................... 32   
 IC_SDA_STUCK_TIMEOUT_DEFAULT ...... 0xffffffff   
 IC_SLV_DATA_NACK_ONLY ............. 0x1   
 IC_10BITADDR_SLAVE ................ 0x0   
 IC_CLK_TYPE ....................... 0x0   
 IC_SMBUS_UDID_MSB ................. 0x0   
 IC_SMBUS_SUSPEND_ALERT ............ 0x0   
 IC_HS_SCL_HIGH_COUNT .............. 0x0006   
 IC_SLV_RESTART_DET_EN ............. 0x1   
 IC_SMBUS .......................... 0x0   
 IC_OPTIONAL_SAR_DEFAULT ........... 0x0   
 IC_PERSISTANT_SLV_ADDR_DEFAULT .... 0x0   
 IC_USE_COUNTS ..................... 0x0   
 IC_RX_BUFFER_DEPTH ................ 16   
 IC_SCL_STUCK_TIMEOUT_DEFAULT ...... 0xffffffff   
 IC_RX_FULL_HLD_BUS_EN ............. 0x1   
 IC_SLAVE_DISABLE .................. 0x1   
 IC_RX_TL .......................... 0x0   
 IC_DEVICE_ID ...................... 0x0   
 IC_HC_COUNT_VALUES ................ 0x0   
 I2C_DYNAMIC_TAR_UPDATE ............ 0   
 IC_SMBUS_CLK_LOW_MEXT_DEFAULT ..... 0xffffffff   
 IC_SMBUS_CLK_LOW_SEXT_DEFAULT ..... 0xffffffff   
 IC_HS_MASTER_CODE ................. 0x1   
 IC_SMBUS_RST_IDLE_CNT_DEFAULT ..... 0xffff   
 IC_SMBUS_UDID_LSB_DEFAULT ......... 0xffffffff   
 IC_SS_SCL_HIGH_COUNT .............. 0x0028   
 IC_SS_SCL_LOW_COUNT ............... 0x002f   
 IC_MAX_SPEED_MODE ................. 0x2   
 IC_STAT_FOR_CLK_STRETCH ........... 0x0   
 IC_STOP_DET_IF_MASTER_ACTIVE ...... 0x0   
 IC_DEFAULT_UFM_SPKLEN ............. 0x1   
 IC_TX_BUFFER_DEPTH ................ 16"]
pub mod i2c0;
#[doc = "DW_apb_i2c address block  

 List of configuration constants for the Synopsys I2C hardware (you may see references to these in I2C register header; these are *fixed* values, set at hardware design time):  

 IC_ULTRA_FAST_MODE ................ 0x0   
 IC_UFM_TBUF_CNT_DEFAULT ........... 0x8   
 IC_UFM_SCL_LOW_COUNT .............. 0x0008   
 IC_UFM_SCL_HIGH_COUNT ............. 0x0006   
 IC_TX_TL .......................... 0x0   
 IC_TX_CMD_BLOCK ................... 0x1   
 IC_HAS_DMA ........................ 0x1   
 IC_HAS_ASYNC_FIFO ................. 0x0   
 IC_SMBUS_ARP ...................... 0x0   
 IC_FIRST_DATA_BYTE_STATUS ......... 0x1   
 IC_INTR_IO ........................ 0x1   
 IC_MASTER_MODE .................... 0x1   
 IC_DEFAULT_ACK_GENERAL_CALL ....... 0x1   
 IC_INTR_POL ....................... 0x1   
 IC_OPTIONAL_SAR ................... 0x0   
 IC_DEFAULT_TAR_SLAVE_ADDR ......... 0x055   
 IC_DEFAULT_SLAVE_ADDR ............. 0x055   
 IC_DEFAULT_HS_SPKLEN .............. 0x1   
 IC_FS_SCL_HIGH_COUNT .............. 0x0006   
 IC_HS_SCL_LOW_COUNT ............... 0x0008   
 IC_DEVICE_ID_VALUE ................ 0x0   
 IC_10BITADDR_MASTER ............... 0x0   
 IC_CLK_FREQ_OPTIMIZATION .......... 0x0   
 IC_DEFAULT_FS_SPKLEN .............. 0x7   
 IC_ADD_ENCODED_PARAMS ............. 0x0   
 IC_DEFAULT_SDA_HOLD ............... 0x000001   
 IC_DEFAULT_SDA_SETUP .............. 0x64   
 IC_AVOID_RX_FIFO_FLUSH_ON_TX_ABRT . 0x0   
 IC_CLOCK_PERIOD ................... 100   
 IC_EMPTYFIFO_HOLD_MASTER_EN ....... 1   
 IC_RESTART_EN ..................... 0x1   
 IC_TX_CMD_BLOCK_DEFAULT ........... 0x0   
 IC_BUS_CLEAR_FEATURE .............. 0x0   
 IC_CAP_LOADING .................... 100   
 IC_FS_SCL_LOW_COUNT ............... 0x000d   
 APB_DATA_WIDTH .................... 32   
 IC_SDA_STUCK_TIMEOUT_DEFAULT ...... 0xffffffff   
 IC_SLV_DATA_NACK_ONLY ............. 0x1   
 IC_10BITADDR_SLAVE ................ 0x0   
 IC_CLK_TYPE ....................... 0x0   
 IC_SMBUS_UDID_MSB ................. 0x0   
 IC_SMBUS_SUSPEND_ALERT ............ 0x0   
 IC_HS_SCL_HIGH_COUNT .............. 0x0006   
 IC_SLV_RESTART_DET_EN ............. 0x1   
 IC_SMBUS .......................... 0x0   
 IC_OPTIONAL_SAR_DEFAULT ........... 0x0   
 IC_PERSISTANT_SLV_ADDR_DEFAULT .... 0x0   
 IC_USE_COUNTS ..................... 0x0   
 IC_RX_BUFFER_DEPTH ................ 16   
 IC_SCL_STUCK_TIMEOUT_DEFAULT ...... 0xffffffff   
 IC_RX_FULL_HLD_BUS_EN ............. 0x1   
 IC_SLAVE_DISABLE .................. 0x1   
 IC_RX_TL .......................... 0x0   
 IC_DEVICE_ID ...................... 0x0   
 IC_HC_COUNT_VALUES ................ 0x0   
 I2C_DYNAMIC_TAR_UPDATE ............ 0   
 IC_SMBUS_CLK_LOW_MEXT_DEFAULT ..... 0xffffffff   
 IC_SMBUS_CLK_LOW_SEXT_DEFAULT ..... 0xffffffff   
 IC_HS_MASTER_CODE ................. 0x1   
 IC_SMBUS_RST_IDLE_CNT_DEFAULT ..... 0xffff   
 IC_SMBUS_UDID_LSB_DEFAULT ......... 0xffffffff   
 IC_SS_SCL_HIGH_COUNT .............. 0x0028   
 IC_SS_SCL_LOW_COUNT ............... 0x002f   
 IC_MAX_SPEED_MODE ................. 0x2   
 IC_STAT_FOR_CLK_STRETCH ........... 0x0   
 IC_STOP_DET_IF_MASTER_ACTIVE ...... 0x0   
 IC_DEFAULT_UFM_SPKLEN ............. 0x1   
 IC_TX_BUFFER_DEPTH ................ 16"]
pub type I2C1 = crate::Periph<i2c0::RegisterBlock, 0x4009_8000>;
impl core::fmt::Debug for I2C1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2C1").finish()
    }
}
#[doc = "DW_apb_i2c address block  

 List of configuration constants for the Synopsys I2C hardware (you may see references to these in I2C register header; these are *fixed* values, set at hardware design time):  

 IC_ULTRA_FAST_MODE ................ 0x0   
 IC_UFM_TBUF_CNT_DEFAULT ........... 0x8   
 IC_UFM_SCL_LOW_COUNT .............. 0x0008   
 IC_UFM_SCL_HIGH_COUNT ............. 0x0006   
 IC_TX_TL .......................... 0x0   
 IC_TX_CMD_BLOCK ................... 0x1   
 IC_HAS_DMA ........................ 0x1   
 IC_HAS_ASYNC_FIFO ................. 0x0   
 IC_SMBUS_ARP ...................... 0x0   
 IC_FIRST_DATA_BYTE_STATUS ......... 0x1   
 IC_INTR_IO ........................ 0x1   
 IC_MASTER_MODE .................... 0x1   
 IC_DEFAULT_ACK_GENERAL_CALL ....... 0x1   
 IC_INTR_POL ....................... 0x1   
 IC_OPTIONAL_SAR ................... 0x0   
 IC_DEFAULT_TAR_SLAVE_ADDR ......... 0x055   
 IC_DEFAULT_SLAVE_ADDR ............. 0x055   
 IC_DEFAULT_HS_SPKLEN .............. 0x1   
 IC_FS_SCL_HIGH_COUNT .............. 0x0006   
 IC_HS_SCL_LOW_COUNT ............... 0x0008   
 IC_DEVICE_ID_VALUE ................ 0x0   
 IC_10BITADDR_MASTER ............... 0x0   
 IC_CLK_FREQ_OPTIMIZATION .......... 0x0   
 IC_DEFAULT_FS_SPKLEN .............. 0x7   
 IC_ADD_ENCODED_PARAMS ............. 0x0   
 IC_DEFAULT_SDA_HOLD ............... 0x000001   
 IC_DEFAULT_SDA_SETUP .............. 0x64   
 IC_AVOID_RX_FIFO_FLUSH_ON_TX_ABRT . 0x0   
 IC_CLOCK_PERIOD ................... 100   
 IC_EMPTYFIFO_HOLD_MASTER_EN ....... 1   
 IC_RESTART_EN ..................... 0x1   
 IC_TX_CMD_BLOCK_DEFAULT ........... 0x0   
 IC_BUS_CLEAR_FEATURE .............. 0x0   
 IC_CAP_LOADING .................... 100   
 IC_FS_SCL_LOW_COUNT ............... 0x000d   
 APB_DATA_WIDTH .................... 32   
 IC_SDA_STUCK_TIMEOUT_DEFAULT ...... 0xffffffff   
 IC_SLV_DATA_NACK_ONLY ............. 0x1   
 IC_10BITADDR_SLAVE ................ 0x0   
 IC_CLK_TYPE ....................... 0x0   
 IC_SMBUS_UDID_MSB ................. 0x0   
 IC_SMBUS_SUSPEND_ALERT ............ 0x0   
 IC_HS_SCL_HIGH_COUNT .............. 0x0006   
 IC_SLV_RESTART_DET_EN ............. 0x1   
 IC_SMBUS .......................... 0x0   
 IC_OPTIONAL_SAR_DEFAULT ........... 0x0   
 IC_PERSISTANT_SLV_ADDR_DEFAULT .... 0x0   
 IC_USE_COUNTS ..................... 0x0   
 IC_RX_BUFFER_DEPTH ................ 16   
 IC_SCL_STUCK_TIMEOUT_DEFAULT ...... 0xffffffff   
 IC_RX_FULL_HLD_BUS_EN ............. 0x1   
 IC_SLAVE_DISABLE .................. 0x1   
 IC_RX_TL .......................... 0x0   
 IC_DEVICE_ID ...................... 0x0   
 IC_HC_COUNT_VALUES ................ 0x0   
 I2C_DYNAMIC_TAR_UPDATE ............ 0   
 IC_SMBUS_CLK_LOW_MEXT_DEFAULT ..... 0xffffffff   
 IC_SMBUS_CLK_LOW_SEXT_DEFAULT ..... 0xffffffff   
 IC_HS_MASTER_CODE ................. 0x1   
 IC_SMBUS_RST_IDLE_CNT_DEFAULT ..... 0xffff   
 IC_SMBUS_UDID_LSB_DEFAULT ......... 0xffffffff   
 IC_SS_SCL_HIGH_COUNT .............. 0x0028   
 IC_SS_SCL_LOW_COUNT ............... 0x002f   
 IC_MAX_SPEED_MODE ................. 0x2   
 IC_STAT_FOR_CLK_STRETCH ........... 0x0   
 IC_STOP_DET_IF_MASTER_ACTIVE ...... 0x0   
 IC_DEFAULT_UFM_SPKLEN ............. 0x1   
 IC_TX_BUFFER_DEPTH ................ 16"]
pub use self::i2c0 as i2c1;
#[doc = "SPI0"]
pub type SPI0 = crate::Periph<spi0::RegisterBlock, 0x4008_0000>;
impl core::fmt::Debug for SPI0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SPI0").finish()
    }
}
#[doc = "SPI0"]
pub mod spi0;
#[doc = "SPI1"]
pub type SPI1 = crate::Periph<spi0::RegisterBlock, 0x4008_8000>;
impl core::fmt::Debug for SPI1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SPI1").finish()
    }
}
#[doc = "SPI1"]
pub use self::spi0 as spi1;
#[doc = "Programmable IO block"]
pub type PIO0 = crate::Periph<pio0::RegisterBlock, 0x5020_0000>;
impl core::fmt::Debug for PIO0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PIO0").finish()
    }
}
#[doc = "Programmable IO block"]
pub mod pio0;
#[doc = "Programmable IO block"]
pub type PIO1 = crate::Periph<pio0::RegisterBlock, 0x5030_0000>;
impl core::fmt::Debug for PIO1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PIO1").finish()
    }
}
#[doc = "Programmable IO block"]
pub use self::pio0 as pio1;
#[doc = "Programmable IO block"]
pub type PIO2 = crate::Periph<pio0::RegisterBlock, 0x5040_0000>;
impl core::fmt::Debug for PIO2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PIO2").finish()
    }
}
#[doc = "Programmable IO block"]
pub use self::pio0 as pio2;
#[doc = "Register block for busfabric control signals and performance counters"]
pub type BUSCTRL = crate::Periph<busctrl::RegisterBlock, 0x4006_8000>;
impl core::fmt::Debug for BUSCTRL {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("BUSCTRL").finish()
    }
}
#[doc = "Register block for busfabric control signals and performance counters"]
pub mod busctrl;
#[doc = "Single-cycle IO block   
 Provides core-local and inter-core hardware for the two processors, with single-cycle access."]
pub type SIO = crate::Periph<sio::RegisterBlock, 0xd000_0000>;
impl core::fmt::Debug for SIO {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SIO").finish()
    }
}
#[doc = "Single-cycle IO block   
 Provides core-local and inter-core hardware for the two processors, with single-cycle access."]
pub mod sio;
#[doc = "Single-cycle IO block   
 Provides core-local and inter-core hardware for the two processors, with single-cycle access."]
pub type SIO_NS = crate::Periph<sio::RegisterBlock, 0xd002_0000>;
impl core::fmt::Debug for SIO_NS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SIO_NS").finish()
    }
}
#[doc = "Single-cycle IO block   
 Provides core-local and inter-core hardware for the two processors, with single-cycle access."]
pub use self::sio as sio_ns;
#[doc = "Additional registers mapped adjacent to the bootram, for use by the bootrom."]
pub type BOOTRAM = crate::Periph<bootram::RegisterBlock, 0x400e_0000>;
impl core::fmt::Debug for BOOTRAM {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("BOOTRAM").finish()
    }
}
#[doc = "Additional registers mapped adjacent to the bootram, for use by the bootrom."]
pub mod bootram;
#[doc = "Coresight block - RP specific registers"]
pub type CORESIGHT_TRACE = crate::Periph<coresight_trace::RegisterBlock, 0x5070_0000>;
impl core::fmt::Debug for CORESIGHT_TRACE {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CORESIGHT_TRACE").finish()
    }
}
#[doc = "Coresight block - RP specific registers"]
pub mod coresight_trace;
#[doc = "USB FS/LS controller device registers"]
pub type USBCTRL_REGS = crate::Periph<usbctrl_regs::RegisterBlock, 0x5011_0000>;
impl core::fmt::Debug for USBCTRL_REGS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("USBCTRL_REGS").finish()
    }
}
#[doc = "USB FS/LS controller device registers"]
pub mod usbctrl_regs;
#[doc = "ARM TrustZone RNG register block"]
pub type TRNG = crate::Periph<trng::RegisterBlock, 0x400f_0000>;
impl core::fmt::Debug for TRNG {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TRNG").finish()
    }
}
#[doc = "ARM TrustZone RNG register block"]
pub mod trng;
#[doc = "Glitch detector controls"]
pub type GLITCH_DETECTOR = crate::Periph<glitch_detector::RegisterBlock, 0x4015_8000>;
impl core::fmt::Debug for GLITCH_DETECTOR {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GLITCH_DETECTOR").finish()
    }
}
#[doc = "Glitch detector controls"]
pub mod glitch_detector;
#[doc = "SNPS OTP control IF (SBPI and RPi wrapper control)"]
pub type OTP = crate::Periph<otp::RegisterBlock, 0x4012_0000>;
impl core::fmt::Debug for OTP {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("OTP").finish()
    }
}
#[doc = "SNPS OTP control IF (SBPI and RPi wrapper control)"]
pub mod otp;
#[doc = "Predefined OTP data layout for RP2350"]
pub type OTP_DATA = crate::Periph<otp_data::RegisterBlock, 0x4013_0000>;
impl core::fmt::Debug for OTP_DATA {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("OTP_DATA").finish()
    }
}
#[doc = "Predefined OTP data layout for RP2350"]
pub mod otp_data;
#[doc = "Predefined OTP data layout for RP2350"]
pub type OTP_DATA_RAW = crate::Periph<otp_data_raw::RegisterBlock, 0x4013_4000>;
impl core::fmt::Debug for OTP_DATA_RAW {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("OTP_DATA_RAW").finish()
    }
}
#[doc = "Predefined OTP data layout for RP2350"]
pub mod otp_data_raw;
#[doc = "For managing simulation testbenches"]
pub type TBMAN = crate::Periph<tbman::RegisterBlock, 0x4016_0000>;
impl core::fmt::Debug for TBMAN {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TBMAN").finish()
    }
}
#[doc = "For managing simulation testbenches"]
pub mod tbman;
#[doc = "DPRAM layout for USB device."]
pub type USBCTRL_DPRAM = crate::Periph<usbctrl_dpram::RegisterBlock, 0x5010_0000>;
impl core::fmt::Debug for USBCTRL_DPRAM {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("USBCTRL_DPRAM").finish()
    }
}
#[doc = "DPRAM layout for USB device."]
pub mod usbctrl_dpram;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "ACCESSCTRL"]
    pub ACCESSCTRL: ACCESSCTRL,
    #[doc = "ADC"]
    pub ADC: ADC,
    #[doc = "BOOTRAM"]
    pub BOOTRAM: BOOTRAM,
    #[doc = "BUSCTRL"]
    pub BUSCTRL: BUSCTRL,
    #[doc = "CLOCKS"]
    pub CLOCKS: CLOCKS,
    #[doc = "CORESIGHT_TRACE"]
    pub CORESIGHT_TRACE: CORESIGHT_TRACE,
    #[doc = "DMA"]
    pub DMA: DMA,
    #[doc = "EPPB"]
    pub EPPB: EPPB,
    #[doc = "GLITCH_DETECTOR"]
    pub GLITCH_DETECTOR: GLITCH_DETECTOR,
    #[doc = "HSTX_CTRL"]
    pub HSTX_CTRL: HSTX_CTRL,
    #[doc = "HSTX_FIFO"]
    pub HSTX_FIFO: HSTX_FIFO,
    #[doc = "I2C0"]
    pub I2C0: I2C0,
    #[doc = "I2C1"]
    pub I2C1: I2C1,
    #[doc = "IO_BANK0"]
    pub IO_BANK0: IO_BANK0,
    #[doc = "IO_QSPI"]
    pub IO_QSPI: IO_QSPI,
    #[doc = "OTP"]
    pub OTP: OTP,
    #[doc = "OTP_DATA"]
    pub OTP_DATA: OTP_DATA,
    #[doc = "OTP_DATA_RAW"]
    pub OTP_DATA_RAW: OTP_DATA_RAW,
    #[doc = "PADS_BANK0"]
    pub PADS_BANK0: PADS_BANK0,
    #[doc = "PADS_QSPI"]
    pub PADS_QSPI: PADS_QSPI,
    #[doc = "PIO0"]
    pub PIO0: PIO0,
    #[doc = "PIO1"]
    pub PIO1: PIO1,
    #[doc = "PIO2"]
    pub PIO2: PIO2,
    #[doc = "PLL_SYS"]
    pub PLL_SYS: PLL_SYS,
    #[doc = "PLL_USB"]
    pub PLL_USB: PLL_USB,
    #[doc = "POWMAN"]
    pub POWMAN: POWMAN,
    #[doc = "PPB"]
    pub PPB: PPB,
    #[doc = "PPB_NS"]
    pub PPB_NS: PPB_NS,
    #[doc = "PSM"]
    pub PSM: PSM,
    #[doc = "PWM"]
    pub PWM: PWM,
    #[doc = "QMI"]
    pub QMI: QMI,
    #[doc = "RESETS"]
    pub RESETS: RESETS,
    #[doc = "ROSC"]
    pub ROSC: ROSC,
    #[doc = "SHA256"]
    pub SHA256: SHA256,
    #[doc = "SIO"]
    pub SIO: SIO,
    #[doc = "SIO_NS"]
    pub SIO_NS: SIO_NS,
    #[doc = "SPI0"]
    pub SPI0: SPI0,
    #[doc = "SPI1"]
    pub SPI1: SPI1,
    #[doc = "SYSCFG"]
    pub SYSCFG: SYSCFG,
    #[doc = "SYSINFO"]
    pub SYSINFO: SYSINFO,
    #[doc = "TBMAN"]
    pub TBMAN: TBMAN,
    #[doc = "TICKS"]
    pub TICKS: TICKS,
    #[doc = "TIMER0"]
    pub TIMER0: TIMER0,
    #[doc = "TIMER1"]
    pub TIMER1: TIMER1,
    #[doc = "TRNG"]
    pub TRNG: TRNG,
    #[doc = "UART0"]
    pub UART0: UART0,
    #[doc = "UART1"]
    pub UART1: UART1,
    #[doc = "USBCTRL_DPRAM"]
    pub USBCTRL_DPRAM: USBCTRL_DPRAM,
    #[doc = "USBCTRL_REGS"]
    pub USBCTRL_REGS: USBCTRL_REGS,
    #[doc = "WATCHDOG"]
    pub WATCHDOG: WATCHDOG,
    #[doc = "XIP_AUX"]
    pub XIP_AUX: XIP_AUX,
    #[doc = "XIP_CTRL"]
    pub XIP_CTRL: XIP_CTRL,
    #[doc = "XOSC"]
    pub XOSC: XOSC,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            RESETS: RESETS::steal(),
            PSM: PSM::steal(),
            CLOCKS: CLOCKS::steal(),
            TICKS: TICKS::steal(),
            PADS_BANK0: PADS_BANK0::steal(),
            PADS_QSPI: PADS_QSPI::steal(),
            IO_QSPI: IO_QSPI::steal(),
            IO_BANK0: IO_BANK0::steal(),
            SYSINFO: SYSINFO::steal(),
            SHA256: SHA256::steal(),
            HSTX_FIFO: HSTX_FIFO::steal(),
            HSTX_CTRL: HSTX_CTRL::steal(),
            EPPB: EPPB::steal(),
            PPB: PPB::steal(),
            PPB_NS: PPB_NS::steal(),
            QMI: QMI::steal(),
            XIP_CTRL: XIP_CTRL::steal(),
            XIP_AUX: XIP_AUX::steal(),
            SYSCFG: SYSCFG::steal(),
            XOSC: XOSC::steal(),
            PLL_SYS: PLL_SYS::steal(),
            PLL_USB: PLL_USB::steal(),
            ACCESSCTRL: ACCESSCTRL::steal(),
            UART0: UART0::steal(),
            UART1: UART1::steal(),
            ROSC: ROSC::steal(),
            POWMAN: POWMAN::steal(),
            WATCHDOG: WATCHDOG::steal(),
            DMA: DMA::steal(),
            TIMER0: TIMER0::steal(),
            TIMER1: TIMER1::steal(),
            PWM: PWM::steal(),
            ADC: ADC::steal(),
            I2C0: I2C0::steal(),
            I2C1: I2C1::steal(),
            SPI0: SPI0::steal(),
            SPI1: SPI1::steal(),
            PIO0: PIO0::steal(),
            PIO1: PIO1::steal(),
            PIO2: PIO2::steal(),
            BUSCTRL: BUSCTRL::steal(),
            SIO: SIO::steal(),
            SIO_NS: SIO_NS::steal(),
            BOOTRAM: BOOTRAM::steal(),
            CORESIGHT_TRACE: CORESIGHT_TRACE::steal(),
            USBCTRL_REGS: USBCTRL_REGS::steal(),
            TRNG: TRNG::steal(),
            GLITCH_DETECTOR: GLITCH_DETECTOR::steal(),
            OTP: OTP::steal(),
            OTP_DATA: OTP_DATA::steal(),
            OTP_DATA_RAW: OTP_DATA_RAW::steal(),
            TBMAN: TBMAN::steal(),
            USBCTRL_DPRAM: USBCTRL_DPRAM::steal(),
        }
    }
}
